### ISSUE TITLE
How to get which objects are collided?

### ISSUE THREAD

**Issue by eguneys** [Rybar/js13k2017#3]
As I understand collision buffer holds colors, so you can test a point to see if it's a color of an object to test if a point collides with an object. But how do you get which object the point collides with?

I want to remove an object on collision, but I can't decide which object the collision happened with.

**Comment by Rybar** [comment]
well collision is just raster data, so you'd have each object check the collision layer during update. It's not meant for object vs. object tracking, just map data. if I remember correctly (it's been a year since I looked at this code) object vs. object was handled elsewhere, or not at all.
